# Existing code...

# New Code to be added
Get-EXOMailbox | Select-Object *,
    @{ Name = 'Mailbox Forward'; Expression = { $_.ForwardingAddress -or $_.ForwardingSmtpAddress } }
# Existing code continuation...