<#
.SYNOPSIS
    Imports M365 Shared Mailboxes from a CSV file created by Export-M365SharedMailboxes.ps1

.DESCRIPTION
    This script reads a CSV file containing shared mailbox configuration and creates or updates
    shared mailboxes in Exchange Online. It includes support for WhatIf mode to preview changes
    before applying them, comprehensive validation, and detailed error handling.

.PARAMETER CsvPath
    The path to the CSV file containing shared mailbox data.
    This should be the file generated by Export-M365SharedMailboxes.ps1

.PARAMETER WhatIf
    Preview changes without actually creating or modifying mailboxes.
    Displays what would happen if the script runs without the WhatIf parameter.

.PARAMETER SkipExisting
    Skip mailboxes that already exist instead of updating them.
    Default behavior is to update existing mailboxes with new settings.

.PARAMETER Force
    Suppress confirmation prompts and proceed with import.

.EXAMPLE
    .\Import-M365SharedMailboxes.ps1 -CsvPath ".\SharedMailboxes_Export_20240210_120000.csv" -WhatIf
    Preview what would be imported without making any changes.

.EXAMPLE
    .\Import-M365SharedMailboxes.ps1 -CsvPath ".\SharedMailboxes_Export_20240210_120000.csv"
    Import shared mailboxes from the CSV file.

.EXAMPLE
    .\Import-M365SharedMailboxes.ps1 -CsvPath ".\SharedMailboxes.csv" -SkipExisting -Force
    Import new mailboxes only, skipping existing ones, without confirmation prompts.

.NOTES
    Requires: ExchangeOnlineManagement module (v3.0.0 or higher)
    Requires: Exchange Administrator role or higher
    Compatible with: PowerShell 5.1 and PowerShell 7+
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory=$true)]
    [ValidateScript({Test-Path $_ -PathType Leaf})]
    [string]$CsvPath,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipExisting,
    
    [Parameter(Mandatory=$false)]
    [switch]$Force
)

#region Functions

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('Info', 'Warning', 'Error', 'Success')]
        [string]$Level = 'Info'
    )
    
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $color = switch ($Level) {
        'Info'    { 'Cyan' }
        'Warning' { 'Yellow' }
        'Error'   { 'Red' }
        'Success' { 'Green' }
    }
    
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
    
    # Also log to file
    $logPath = $CsvPath -replace '\.csv$', '_import.log'
    "[$timestamp] [$Level] $Message" | Out-File -FilePath $logPath -Append -Encoding UTF8
}

function Test-ExchangeOnlineConnection {
    try {
        $null = Get-OrganizationConfig -ErrorAction Stop
        return $true
    }
    catch {
        return $false
    }
}

function Connect-ExchangeOnlineIfNeeded {
    Write-Log "Checking Exchange Online connection..." -Level Info
    
    if (-not (Test-ExchangeOnlineConnection)) {
        Write-Log "Not connected to Exchange Online. Initiating connection..." -Level Warning
        
        try {
            Connect-ExchangeOnline -ShowBanner:$false -ErrorAction Stop
            Write-Log "Successfully connected to Exchange Online" -Level Success
        }
        catch {
            Write-Log "Failed to connect to Exchange Online: $($_.Exception.Message)" -Level Error
            throw
        }
    }
    else {
        Write-Log "Already connected to Exchange Online" -Level Success
    }
}

function Test-MailboxExists {
    param(
        [string]$Identity
    )
    
    try {
        $mailbox = Get-Mailbox -Identity $Identity -ErrorAction SilentlyContinue
        return ($null -ne $mailbox)
    }
    catch {
        return $false
    }
}

function New-SharedMailboxFromCsv {
    param(
        [PSCustomObject]$MailboxData,
        [bool]$WhatIfMode
    )
    
    $displayName = $MailboxData.'Source Display Name'
    $primaryEmail = $MailboxData.'Source Email Address'
    
    if ($WhatIfMode) {
        Write-Log "[WHATIF] Would create shared mailbox: $displayName ($primaryEmail)" -Level Info
        return $true
    }
    
    try {
        $mailboxParams = @{
            Name = $displayName
            DisplayName = $displayName
            PrimarySmtpAddress = $primaryEmail
            Shared = $true
            ErrorAction = 'Stop'
        }
        
        $newMailbox = New-Mailbox @mailboxParams
        Write-Log "Created shared mailbox: $displayName" -Level Success
        return $newMailbox
    }
    catch {
        Write-Log "Failed to create mailbox $displayName : $($_.Exception.Message)" -Level Error
        return $null
    }
}

function Set-MailboxAliases {
    param(
        [string]$Identity,
        [string]$Aliases,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($Aliases)) {
        return
    }
    
    $aliasList = $Aliases -split ';' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    
    foreach ($alias in $aliasList) {
        if ($WhatIfMode) {
            Write-Log "[WHATIF] Would add alias $alias to $Identity" -Level Info
        }
        else {
            try {
                Set-Mailbox -Identity $Identity -EmailAddresses @{Add="smtp:$alias"} -ErrorAction Stop
                Write-Verbose "Added alias: $alias"
            }
            catch {
                Write-Log "Failed to add alias $alias to $Identity : $($_.Exception.Message)" -Level Warning
            }
        }
    }
}

function Set-MailboxPermissions {
    param(
        [string]$Identity,
        [string]$Members,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($Members)) {
        return
    }
    
    $memberList = $Members -split ';' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    
    foreach ($member in $memberList) {
        if ($WhatIfMode) {
            Write-Log "[WHATIF] Would grant FullAccess to $member on $Identity" -Level Info
        }
        else {
            try {
                Add-MailboxPermission -Identity $Identity -User $member -AccessRights FullAccess -InheritanceType All -ErrorAction Stop | Out-Null
                Write-Verbose "Granted FullAccess to: $member"
            }
            catch {
                Write-Log "Failed to grant FullAccess to $member on $Identity : $($_.Exception.Message)" -Level Warning
            }
        }
    }
}

function Set-SendOnBehalfPermissions {
    param(
        [string]$Identity,
        [string]$Users,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($Users)) {
        return
    }
    
    $userList = $Users -split ';' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    
    if ($WhatIfMode) {
        Write-Log "[WHATIF] Would grant SendOnBehalf to: $($userList -join ', ') on $Identity" -Level Info
    }
    else {
        try {
            Set-Mailbox -Identity $Identity -GrantSendOnBehalfTo $userList -ErrorAction Stop
            Write-Verbose "Granted SendOnBehalf permissions"
        }
        catch {
            Write-Log "Failed to set SendOnBehalf permissions on $Identity : $($_.Exception.Message)" -Level Warning
        }
    }
}

function Set-MailboxArchive {
    param(
        [string]$Identity,
        [string]$ArchiveStatus,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($ArchiveStatus) -or $ArchiveStatus -eq "Unknown") {
        return
    }
    
    if ($ArchiveStatus -eq "Enabled") {
        if ($WhatIfMode) {
            Write-Log "[WHATIF] Would enable archive on $Identity" -Level Info
        }
        else {
            try {
                Enable-Mailbox -Identity $Identity -Archive -ErrorAction Stop | Out-Null
                Write-Verbose "Enabled archive"
            }
            catch {
                Write-Log "Failed to enable archive on $Identity : $($_.Exception.Message)" -Level Warning
            }
        }
    }
}

function Set-MailboxLitigationHold {
    param(
        [string]$Identity,
        [string]$LegalHold,
        [string]$Duration,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($LegalHold) -or $LegalHold -ne "Enabled") {
        return
    }
    
    if ($WhatIfMode) {
        $msg = "[WHATIF] Would enable litigation hold on $Identity"
        if (-not [string]::IsNullOrWhiteSpace($Duration)) {
            $msg += " with duration: $Duration"
        }
        Write-Log $msg -Level Info
    }
    else {
        try {
            $params = @{
                Identity = $Identity
                LitigationHoldEnabled = $true
                ErrorAction = 'Stop'
            }
            
            if (-not [string]::IsNullOrWhiteSpace($Duration)) {
                $params.LitigationHoldDuration = $Duration
            }
            
            Set-Mailbox @params
            Write-Verbose "Enabled litigation hold"
        }
        catch {
            Write-Log "Failed to enable litigation hold on $Identity : $($_.Exception.Message)" -Level Warning
        }
    }
}

function Set-RequireSenderAuth {
    param(
        [string]$Identity,
        [string]$RequireAuth,
        [bool]$WhatIfMode
    )
    
    if ([string]::IsNullOrWhiteSpace($RequireAuth)) {
        return
    }
    
    $authRequired = $RequireAuth -eq "True" -or $RequireAuth -eq $true
    
    if ($WhatIfMode) {
        Write-Log "[WHATIF] Would set RequireSenderAuthenticationEnabled to $authRequired on $Identity" -Level Info
    }
    else {
        try {
            Set-Mailbox -Identity $Identity -RequireSenderAuthenticationEnabled $authRequired -ErrorAction Stop
            Write-Verbose "Set RequireSenderAuthenticationEnabled to $authRequired"
        }
        catch {
            Write-Log "Failed to set RequireSenderAuthenticationEnabled on $Identity : $($_.Exception.Message)" -Level Warning
        }
    }
}

function Import-SharedMailbox {
    param(
        [PSCustomObject]$MailboxData,
        [bool]$WhatIfMode,
        [bool]$SkipIfExists
    )
    
    $displayName = $MailboxData.'Source Display Name'
    $primaryEmail = $MailboxData.'Source Email Address'
    
    # Validate required fields
    if ([string]::IsNullOrWhiteSpace($displayName) -or [string]::IsNullOrWhiteSpace($primaryEmail)) {
        Write-Log "Skipping mailbox with missing Display Name or Email Address" -Level Warning
        return $false
    }
    
    Write-Log "Processing: $displayName ($primaryEmail)" -Level Info
    
    # Check if mailbox exists
    $mailboxExists = Test-MailboxExists -Identity $primaryEmail
    
    if ($mailboxExists) {
        if ($SkipIfExists) {
            Write-Log "Mailbox $displayName already exists - skipping (SkipExisting flag set)" -Level Warning
            return $false
        }
        else {
            Write-Log "Mailbox $displayName already exists - will update settings" -Level Info
        }
    }
    else {
        # Create new mailbox
        $newMailbox = New-SharedMailboxFromCsv -MailboxData $MailboxData -WhatIfMode $WhatIfMode
        if (-not $newMailbox -and -not $WhatIfMode) {
            return $false
        }
        
        # Wait a bit for mailbox to be fully created
        if (-not $WhatIfMode) {
            Start-Sleep -Seconds 5
        }
    }
    
    # Configure mailbox settings
    try {
        # Set email aliases
        Set-MailboxAliases -Identity $primaryEmail -Aliases $MailboxData.'Source Email Alias(es)' -WhatIfMode $WhatIfMode
        
        # Set permissions
        Set-MailboxPermissions -Identity $primaryEmail -Members $MailboxData.'Source Members' -WhatIfMode $WhatIfMode
        
        # Set SendOnBehalf
        Set-SendOnBehalfPermissions -Identity $primaryEmail -Users $MailboxData.'Grant Send On Behalf' -WhatIfMode $WhatIfMode
        
        # Set RequireSenderAuth
        Set-RequireSenderAuth -Identity $primaryEmail -RequireAuth $MailboxData.'Require Sender Auth' -WhatIfMode $WhatIfMode
        
        # Set Archive
        Set-MailboxArchive -Identity $primaryEmail -ArchiveStatus $MailboxData.'Archive Status' -WhatIfMode $WhatIfMode
        
        # Set Litigation Hold
        Set-MailboxLitigationHold -Identity $primaryEmail -LegalHold $MailboxData.'Legal Hold' -Duration $MailboxData.'Litigation Duration' -WhatIfMode $WhatIfMode
        
        if (-not $WhatIfMode) {
            Write-Log "Successfully processed: $displayName" -Level Success
        }
        return $true
    }
    catch {
        Write-Log "Error configuring mailbox $displayName : $($_.Exception.Message)" -Level Error
        return $false
    }
}

#endregion

#region Main Script

try {
    Write-Log "========================================" -Level Info
    Write-Log "M365 Shared Mailbox Import Script" -Level Info
    Write-Log "========================================" -Level Info
    Write-Log "" -Level Info
    
    if ($WhatIfPreference) {
        Write-Log "RUNNING IN WHATIF MODE - No changes will be made" -Level Warning
        Write-Log "" -Level Info
    }
    
    # Check for required module
    Write-Log "Checking for ExchangeOnlineManagement module..." -Level Info
    $module = Get-Module -ListAvailable -Name ExchangeOnlineManagement | Sort-Object Version -Descending | Select-Object -First 1
    
    if (-not $module) {
        Write-Log "ExchangeOnlineManagement module not found!" -Level Error
        Write-Log "Please install it using: Install-Module -Name ExchangeOnlineManagement -Force" -Level Error
        throw "Required module not found"
    }
    
    if ($module.Version -lt [Version]"3.0.0") {
        Write-Log "ExchangeOnlineManagement version $($module.Version) found, but 3.0.0 or higher is recommended" -Level Warning
    }
    else {
        Write-Log "ExchangeOnlineManagement version $($module.Version) found" -Level Success
    }
    
    # Import module
    Import-Module ExchangeOnlineManagement -ErrorAction Stop
    
    # Connect to Exchange Online
    if (-not $WhatIfPreference) {
        Connect-ExchangeOnlineIfNeeded
    }
    else {
        Write-Log "Skipping Exchange Online connection in WhatIf mode" -Level Info
    }
    
    # Read CSV file
    Write-Log "Reading CSV file: $CsvPath" -Level Info
    
    try {
        $mailboxData = Import-Csv -Path $CsvPath -Encoding UTF8 -ErrorAction Stop
    }
    catch {
        Write-Log "Failed to read CSV file: $($_.Exception.Message)" -Level Error
        throw
    }
    
    $totalMailboxes = @($mailboxData).Count
    Write-Log "Found $totalMailboxes mailbox(es) in CSV file" -Level Success
    Write-Log "" -Level Info
    
    # Validate CSV structure
    $requiredColumns = @(
        'Source Display Name',
        'Source Email Address'
    )
    
    $csvColumns = $mailboxData[0].PSObject.Properties.Name
    $missingColumns = $requiredColumns | Where-Object { $_ -notin $csvColumns }
    
    if ($missingColumns) {
        Write-Log "CSV file is missing required columns: $($missingColumns -join ', ')" -Level Error
        throw "Invalid CSV file structure"
    }
    
    # Confirm before proceeding
    if (-not $Force -and -not $WhatIfPreference) {
        Write-Log "About to import $totalMailboxes shared mailbox(es)" -Level Warning
        $response = Read-Host "Do you want to continue? (Y/N)"
        
        if ($response -ne 'Y' -and $response -ne 'y') {
            Write-Log "Import cancelled by user" -Level Warning
            return
        }
        Write-Log "" -Level Info
    }
    
    # Initialize counters
    $successCount = 0
    $failureCount = 0
    $skippedCount = 0
    $counter = 0
    
    # Process each mailbox
    foreach ($mailbox in $mailboxData) {
        $counter++
        $percentComplete = [math]::Round(($counter / $totalMailboxes) * 100)
        
        Write-Progress -Activity "Importing Shared Mailboxes" -Status "Processing $($mailbox.'Source Display Name') ($counter of $totalMailboxes)" -PercentComplete $percentComplete
        
        $result = Import-SharedMailbox -MailboxData $mailbox -WhatIfMode $WhatIfPreference -SkipIfExists $SkipExisting
        
        if ($result) {
            $successCount++
        }
        else {
            if (Test-MailboxExists -Identity $mailbox.'Source Email Address' -and $SkipExisting) {
                $skippedCount++
            }
            else {
                $failureCount++
            }
        }
        
        Write-Log "" -Level Info
    }
    
    Write-Progress -Activity "Importing Shared Mailboxes" -Completed
    
    # Display summary
    Write-Log "========================================" -Level Info
    Write-Log "Import Summary" -Level Info
    Write-Log "========================================" -Level Info
    Write-Log "Total Mailboxes in CSV: $totalMailboxes" -Level Info
    Write-Log "Successfully Processed: $successCount" -Level Success
    Write-Log "Skipped (Already Exist): $skippedCount" -Level Warning
    Write-Log "Failed: $failureCount" -Level Error
    Write-Log "Log File: $($CsvPath -replace '\.csv$', '_import.log')" -Level Info
    Write-Log "========================================" -Level Info
    
    if ($WhatIfPreference) {
        Write-Log "" -Level Info
        Write-Log "This was a WhatIf run - no actual changes were made" -Level Warning
        Write-Log "Run without -WhatIf to apply changes" -Level Info
    }
}
catch {
    Write-Log "Script execution failed: $($_.Exception.Message)" -Level Error
    Write-Log "Stack Trace: $($_.ScriptStackTrace)" -Level Error
    throw
}
finally {
    Write-Log "" -Level Info
    Write-Log "Script execution completed" -Level Info
}

#endregion
